- rootdir/vendor/etc/fstab.tama
On kernel 4.9, /sys/devices/soc has been moved
to /sys/devices/platform/soc.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
> [master] fstab: Update paths for k4.9

- rootdir/vendor/ueventd.rc
On kernel 4.9, /sys/devices/soc has been moved
to /sys/devices/platform/soc.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
> [o-mr1] ueventd.rc: Update paths for kernel 4.9

- rootdir/vendor/ueventd.rc
On kernel 4.9, /sys/devices/soc has been moved
to /sys/devices/platform/soc.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
> [master] ueventd.rc: Update paths for kernel 4.9

- rootdir/vendor/ueventd.rc
The ueventd file had definitions for k4.4 SDM630: fix them for
k4.9 SDM845.
> [TAMA] ueventd: Fix sysfs paths for LEDs and backlight

- rootdir/vendor/etc/media_codecs.xml
10-18 15:29:20.052   786   786 E MediaCodecsXmlParser: Cannot find the role for a decoder of type audio/x-ms-wma
10-18 15:29:20.052   786   786 E MediaCodecsXmlParser: Cannot find the role for a decoder of type audio/alac
10-18 15:29:20.052   786   786 E MediaCodecsXmlParser: Cannot find the role for a decoder of type audio/dsd
10-18 15:29:20.052   786   786 E MediaCodecsXmlParser: Cannot find the role for a decoder of type video/divx4
10-18 15:29:20.052   786   786 E MediaCodecsXmlParser: Cannot find the role for a decoder of type video/divx
10-18 15:29:20.052   786   786 E MediaCodecsXmlParser: Cannot find the role for a decoder of type video/x-ms-wmv
Bunch of codecs that we do not support
Couldnt find these codecs in the other platform gits
> Cleanup o mr

- rootdir/vendor/etc/fstab.tama
Starting from Android P, it is possible to use FBE in combination with adoptable storage.
This also has the side effect that Android will actually start scanning external sdcards for media.
> rootdir: vendor: fstab: add encryptable flag for external sdcards

- sepolicy_platform/genfs_contexts
following crosshatch https://android.googlesource.com/device/google/crosshatch-sepolicy/+/android-9.0.0_r21/vendor/qcom/common/genfs_contexts#62
avoid
09-28 21:10:07.889   725   725 I pd-mapper: type=1400 audit(0.0:8): avc: denied { read } for name=name dev=sysfs ino=67870 scontext=u:r:pd_mapper:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
09-28 21:10:07.889   725   725 I pd-mapper: type=1400 audit(0.0:9): avc: denied { open } for path=/sys/devices/platform/soc/8300000.qcom,turing/subsys6/name dev=sysfs ino=67870 scontext=u:r:pd_mapper:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
> label 8300000.qcom,turing as sysfs_msm_subsys

- rootdir/vendor/etc/init/init.tama.rc
Taken from stock init scripts, where the restart levels of some subsystems are changed.
This avoids crashing the whole system when one of the subsystems crashes.
> rootdir: init: setup restart levels for subsystems

- sepolicy_platform/genfs_contexts
following crosshatch
https://android.googlesource.com/device/google/crosshatch-sepolicy/+/android-9.0.0_r21/vendor/qcom/common/genfs_contexts#60
avoid
10-10 17:55:30.839   728   728 I pm-service: type=1400 audit(0.0:6): avc: denied { open } for path=/sys/devices/platform/soc/soc:qcom,ipa_fws/subsys2/name dev=sysfs ino=51410 scontext=u:r:per_mgr:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
> label soc:qcom,ipa_fws as sysfs_msm_subsys

- rootdir/vendor/etc/fstab.tama
Since there is no longer a command in init.common.rc that remounts as read-only, set the property directly in fstab.
> [tama] fstab: Mount dsp partition read-only

- rootdir/vendor/etc/init/init.tama.pwr.rc
With rqbalance there is sub-par performance with the
sort of rendundant schedutil governor.
Setup the interactive governor to get back our balanced
battery saving and improved perfomance.
> [TAMA] Switch and configure interactive governor

- rootdir/vendor/etc/rqbalance_config.xml
The Tama platform had a wrong rqbalance configuration
taken from another platform for early bringup.
Time to use the right one!
> [TAMA] vendor: rqbalance_config: Redo configuration for Tama

- sepolicy_platform/genfs_contexts
1-22 14:56:48.511   720   720 I health@2.0-serv: type=1400 audit(0.0:273): avc: denied { getattr } for path=/sys/devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pmi8998@2:qcom,qpnp-smb2/power_supply/pc_port/online dev=sysfs ino=57588 scontext=u:r:hal_health_default:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=file permissive=1
> sepolicy: label pc_port as sysfs_batteryinfo

- sepolicy_platform/genfs_contexts
needed for Enforcing SELinux
akari:/sys/class/backlight # ls -l
total 0
lrwxrwxrwx 1 root root 0 1970-10-28 11:52 panel0-backlight -> ../../devices/platform/soc/ae00000.qcom,mdss_mdp/backlight/panel0-backlight
> sepolicy: label SDE path as sysfs_leds

- sepolicy_platform/genfs_contexts
health is trying to read /type under these paths
[    3.964888] type=1400 audit(26114220.939:5): avc: denied { read } for pid=702 comm=android.hardwar name=type dev=sysfs ino=57484 scontext=u:r:hal_health_default:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=file permissive=0
[    3.966788] type=1400 audit(26114220.939:6): avc: denied { read } for pid=702 comm=android.hardwar name=type dev=sysfs ino=57562 scontext=u:r:hal_health_default:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=file permissive=0
[    3.967052] type=1400 audit(26114220.939:7): avc: denied { read } for pid=702 comm=android.hardwar name=type dev=sysfs ino=57515 scontext=u:r:hal_health_default:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=file permissive=0
[    3.967238] type=1400 audit(26114220.939:8): avc: …
> sepolicy: label all smb2/power_supply paths

- PlatformConfig.mk
With https://github.com/sonyxperiadev/kernel-defconfig/pull/27
Virtual framebuffers are used to debug the fbdev system, and should not be used on production devices. It only wastes memory.
Tested on SoMC Akatsuki DSDS (with removal in `tama` repo) and SoMC Discovery SDE.
> PlatformConfig: Remove vfb bootarg for testing fbdev.

- sepolicy_platform/genfs_contexts
health is trying to access it to read /type
akari:/sys/class/power_supply # ls -l
lrwxrwxrwx 1 root root 0 1970-10-30 11:07 wireless -> ../../devices/platform/soc/a88000.i2c/i2c-0/0-0061/power_supply/wireless
> sepolicy: label wireless_charger as sysfs_batteryinfo

- platform.mk
dtbo contains parts of the dt that are prone to being updated just like the dt found in the boot image.
Make sure it is included in ota updates.
> platform: add dtbo to ota partitions

- rootdir/vendor/etc/audio_platform_info.xml
Use SPEAKER_PROTECTION ACDB ID for SPEAKER even though speaker
protection is not supported.
The SPEAKER_PROTECTION ACDB ID is calibrated and if we run it with
speaker protection not enabled then speakers will be driven safer.
> audio_platform_info: Change SPEAKER ACDB ID

- rootdir/vendor/etc/msm_irqbalance.conf
The IRQ numbers set as ignored were wrong and corresponded to interrupts other than the ones listed.
> rootdir: vendor: correct ignored IRQs

- PlatformConfig.mk
This is a platform configuration that never changes in the entire life
of a specific kernel version: there is no need to set it in the external
cmdline that comes from the boot image.
Starting from kernel 4.14 this setting is pushed through the bootargs
specified in kernel, in the device-tree for the specific platform.
> [TAMA-4.14] PlatformConfig: Remove dsi display selection from external cmdline

- rootdir/vendor/etc/init/init.tama.rc
This platform kills apps too easily and that's due to the very
aggressive caching that happens in background, which is
totally fine, but there is no point in forcing to have a lot of
free, unused and wasted memory apart a lil faster allocation
in some cases.
In - any - case though, the overhead of having to free memory
by closing userspace apps is way bigger than the overhead that
we get by some memory fragmentation here and there or
reclaim when a very large amount of memory needs to be used
by a very large application.
For this reason, prefer a great instant-app-reopening user
experience over 1% less time to open giant games.
Tested on SoMC Tama Akatsuki RoW
> [TAMA] init: Set custom forced LowMemoryKiller minfree params

- Android.bp
- bluetooth/bdroid_buildcfg.h
- bootctrl/Android.bp
- platform.mk
Welcome Tama on Android Q!
We convert the bootctrl HAL to BP (shared library implementation) and set up the namespace for it.
*Please* discuss ` bluetooth/bdroid_buildcfg.h`. We should find a better solution... The compiler is configured to be much more strict.
> [RFC/WIP] [Android 10] New-style bootctrl, continued bdroid_buildcfg woes

- platform.mk
Android 10 changed the way libhardware is allowed to find modules, and
this doesn't work through symlinks anymore. For more information, see
the commit that removes the symlink from hardware/camera/Android.mk in
common, and the relevant change in libhardware:
https://android.googlesource.com/platform/hardware/libhardware/+/e448a05fecab601c59b89a2f948e1ad18050e40f%5E%21/#F0
Instead, set the vendor variant propery, that points libhardware to load
camera.qcom.so from any of the predefined search folders.
I don't think
```make
PRODUCT_PACKAGES += \
camera.sdm845
```
is warranted anymore.
> camera: Set the hardware variant to `qcom'.

- platform.mk
The Tama platform requires a 64 bit camera HAL.
> platform: use 64 bit camera implementation

- rootdir/vendor/etc/init/init.tama.rc
Grant write permission to group to stop issues when the WiFi HAL
or other components using this is/are started as an user different
from "wifi".
> [TAMA] init.tama.rc: Set 0664 permissions to wlan fwpath

- rootdir/vendor/ueventd.rc
On kernel 4.14 we've got a new driver for Tri-LED that adheres
...mostly... to the standard Linux way of dealing with LEDs.
Though, paths have changed!
> [TAMA] ueventd: Fix Tri-LED path permissions

- overlay/frameworks/base/core/res/res/values/config.xml
- platform.mk
- rootdir/vendor/usr/idc/uinput-fpc.idc
- rootdir/vendor/usr/keylayout/uinput-fpc.kl
For https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/pull/50
These config files are used to tie uinput events coming from `uinput-fpc` to semantic names that are understood by Android.
> [Tama] [5/7] Enable FPC gestures

- platform.mk
When creating an otapackage, we definitely want to also push the
vbmeta in order to get the verifier to work as intended, otherwise
the only solution would be to disable verification in the vbmeta,
leading to big security issues.
> [TAMA] platform: Add vbmeta to AB_OTA_PARTITIONS

- rootdir/vendor/etc/rqbalance_config.xml
Android 10 needs a little more power when executing background
tasks while the device is in power saving mode (display off or battery
saver enabled).
The need for more power is especially seen during bluetooth audio
playback while the display is off.
> [TAMA] vendor: rqbalance: Update configuration for Android 10

- rootdir/vendor/firmware/wlan/qca_cld/WCNSS_qcom_cfg.ini
Configure WCNSS to expose a secondary interface, wlan1, which is used
for concurrent AP while wlan0 runs the STA.
> [TAMA] WCNSS: Enable concurrent STA/AP on wlan1 interface.

- rootdir/vendor/etc/camera/camxoverridesettings.txt
Let Dual IFE to keep defaults as it's required in some cases.
Set back results timeout to default: 10 is a too small value and
we trigger timeout, producing useless logging and triggering
recovery after some time, hence slowing down the entire UX.
> [COMMON] camxoverridesettings: Enable Dual IFE, set results timeout to default

- overlay/frameworks/base/core/res/res/values/config.xml
Tama devices support this sensor and odm compatibility is introduced in
v5: when the device is locked, hold the phone up like you're about to
take a picture and the camera opens.
> [TAMA] overlay: configure camera lift trigger sensor

- platform.mk
- rootdir/vendor/etc/audio_policy_configuration.xml
- rootdir/vendor/etc/audio_policy_configuration_bluetooth_legacy_hal.xml
- rootdir/vendor/etc/common_primary_audio_policy_configuration.xml
The audio.bluetooth.default.so audio module, configured by
bluetooth_audio_policy_configuration.xml, utilizes the new HAL-based
mechanism to register a BT audio endpoint and transfer audio data.
Update our policy to route audio properly to this module, while
retaining a2dp input compatibility through the old mechanism.
See the identical change in crosshatch:
https://android.googlesource.com/device/google/crosshatch/+/c05ccdbed6c7c74d450e7149969c6c3431155628
audio_policy_configuration_bluetooth_legacy_hal.xml remains unchanged to
reflect the old variant of the system (using sockets between the BT
stack and audioserver), usable with
persist.bluetooth.bluetooth_audio_hal.disabled=true.
NOTE: This relies on device-sony-common to add the new files to
PRODUCT_COPY_FILES.
> [TAMA] audio_policy: Migrate to bluetooth.audio@2.0 HAL policy

- platform.mk
- rootdir/vendor/etc/sound_trigger_mixer_paths_wcd9340.xml
- rootdir/vendor/etc/sound_trigger_platform_info.xml
This adds the Sound Trigger configuration for the SoMC SDM845
Kumano platform, imported from stock release 52.1.A.0.532.
> [TAMA] platform: Add sound trigger configuration for SoMC SDM845 Tama

- platform.mk
- rootdir/vendor/usr/keylayout/uinput-fpc.kl
Apollo's fingerprint sensor is rotated 90 degrees clockwise, as compared to Akari and Akatsuki.
This necessitates two different config files, and as such, the keylayout configs are moved to the individual device gits.
See:
https://github.com/sonyxperiadev/device-sony-apollo/pull/26
https://github.com/sonyxperiadev/device-sony-akari/pull/25
https://github.com/sonyxperiadev/device-sony-akatsuki/pull/21
> rootdir: Move uinput-fpc.kl to devices

- platform.mk
Configure the audio buffers for fast mapping, allowing for
latency reduction on audio paths.
> [TAMA] platform: Configure audio buffer for fast mapping

- sepolicy_platform/file_contexts
`gpt_block_device` is a custom SODP invention while AOSP already defines `root_block_device` for exactly this purpose; that is already used for `mmcblk0` on MMC platforms.
> [TAMA] [Q/R] sepolicy: Use root_block_device for sda instead of gpt_block_device

- rootdir/vendor/etc/init/init.tama.pwr.rc
in the 4.14 kernel these configs are deprecated and should be removed to get rid of irrelevant errors in dmesg/logcat.
> init.tama.pwr.rc: remove deprecated configs
